language: node_js
node_js:
  - "stable"

cache:
  directories:
    - node_modules

notifications:
  email:
    - recipients:
        - andrew.e.kimberly@gmail.com

jobs:
  include:
    - stage: build
      script: npm run build

    - stage: test
      script:
        - npm run check
        - npm run test -- --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
